### ISSUE TITLE
Linebreak Error

### ISSUE THREAD

**Issue by bonnyface** [JulianDuggan/ctotopdf#1] opened 2019-02-23 16:34 UTC
I am  running the code below and getting the error "Option Linebreak(3) not allowed". How can i fix this?

ctopdf using "X:/Downloads/Copy of SHEP Follow Up 2019 year2.xlsx", save("X:/Downloads") merge skiplist(98 (1) 99) title(Follow Up 2019 Survey) date(23.02.19) version(1) authors(Bonnyface) choicelength(2) coverimage("X:/Downloads/cover3.png") packages

![linebreak error](https://user-images.githubusercontent.com/47923931/53289038-ae987480-37a1-11e9-8447-b2fdfa77a7e9.PNG)

**Comment by JulianDuggan** [comment] 2019-02-23 17:24
Hi There, 

Thanks very much for testing out the program! I am not sure on the basis of this trace alone what is going wrong, but if you'd feel comfortable sending me "Copy of SHEP Follow Up 2019 year2.xlsx", I would be happy to debug it for you. 

Best,

Julian

**Comment by bonnyface** [comment] 2019-02-23 18:17
Thanks Julian for the quick response.

Please find attached the cto form attached
.......................................................


     *

**Comment by JulianDuggan** [comment] 2019-02-23 18:31
Sorry, not seeing an attachment. Try leaving it from the github website instead of by email?

**Comment by bonnyface** [comment] 2019-02-23 18:45
[Follow Up 2019 Survey.xlsx](https://github.com/JulianDuggan/ctopdf/files/2897131/Follow.Up.2019.Survey.xlsx)

**Comment by bonnyface** [comment] 2019-02-23 18:46
Hi Julian,

I just shared on github

Thank you
.......................................................


*Skype: b.ndunguMob: (+254) 720 024 443      *

**Comment by JulianDuggan** [comment] 2019-02-24 20:09
So I'm actually hitting a different error altogether -- the choice labels "acts" and "source" used in your survey sheet don't have any corresponding definitions in the choices sheet. Try fixing this and let me know if the problem persists?

**Comment by bonnyface** [comment] 2019-02-24 21:23
Hi Julian,

Please find attached
[Follow Up 2019 Survey.xlsx](https://github.com/JulianDuggan/ctopdf/files/2898408/Follow.Up.2019.Survey.xlsx)

**Comment by bonnyface** [comment] 2019-02-25 17:56
Hi Julian,

Any updates on this issue?

**Comment by JulianDuggan** [comment] 2019-02-26 00:00
Hi, 

So I am encountering the same error, that choice labels source and acts from lines 1158 and 1160 do not have corresponding values defined in the chioces sheet. I did find two choice labels named shepsource and shepacts defined in part the choices sheet, so I manually changed these two lines to match these two choice labels. Upon doing that, I ran the command exactly as you wrote it, and the program produced a merged pdf for me (I can email it to you, if you would like to see it. I assume you don't want me to post it here online for anyone to see.)

So I think the problem is likely on lines 1158 and 1160. Correct your value label names, and if you still have issues, let me know. 

Best,

Julian

**Comment by bonnyface** [comment] 2019-02-26 05:00
Hi Julian,

I fixed that and it takes me back to the same error of linebreak(3). I have made additional changes on the survey and I am attaching the recent one. Feel free to share the PDF output on my email (bonfacendungu@gmail.com)

![image](https://user-images.githubusercontent.com/47923931/53388484-609b9080-399c-11e9-9c6f-917c7055eba5.png)
[Follow.Up.2019.Survey.xlsx](https://github.com/JulianDuggan/ctopdf/files/2903839/Follow.Up.2019.Survey.xlsx)

**Comment by JulianDuggan** [comment] 2019-02-26 05:05
Huh, that is pretty odd. Try checking for updates in your version of putpdf
/ STATA (update all) ?

I will email you what worked for me.

Best,

Julian

**Comment by JulianDuggan** [comment] 2019-02-26 05:07
(I would also reccomend specifying the option loudvars to see where the
program is breaking for you. Maybe you can figure out what line is causing
the issue and work backwards from there)

**Comment by bonnyface** [comment] 2019-02-26 07:50
Seems it was an version/update issue. Its now working. Thank you so much

![image](https://user-images.githubusercontent.com/47923931/53395900-20e0a300-39b4-11e9-8806-b3a2572c1afd.png)

**Closed as completed** 2019-03-18 18:51 UTC
